PulseGamingMVC/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.EntityFrameworkCore;
using MvcCoreAzureStorage.Services;
using PulseGamingMVC.Data;
using PulseGamingMVC.Helpers;
using PulseGamingMVC.Models;
using PulseGamingMVC.Repositories;
using PulseGamingMVC.Services;
using System.Drawing.Text;
using static System.Runtime.InteropServices.JavaScript.JSType;

#region PROCEDIMIENTOS ALMACENADOS

//create procedure SP_DETALLES_USUARIO
//(@IDUsuario int)
//as
//	select * from Usuarios where IDUsuario = @IDUsuario 
//go

#endregion

namespace PulseGamingMVC.Controllers
{
    public class AdminController : Controller
    {
        private ServiceStorageBlobs storageBlobs;
        private IRepositoryJuegos repoGame;
        private IRepositoryUsuarios repoUsu;
        private ServicePulseGaming service;

        private ListasCrearJuego listasCrearJuego = new ListasCrearJuego();

        public AdminController(IRepositoryJuegos repoGame, IRepositoryUsuarios repoUsu, ServiceStorageBlobs storageBlobs, ServicePulseGaming service)
        {
            this.repoGame = repoGame;
            this.repoUsu = repoUsu;
            this.storageBlobs = storageBlobs;
            this.service = service;
        }

        public IActionResult Dashboard()
        {
            return View();
        }

        //USUARIOS
        public async Task<IActionResult> UsuariosView()
        {
            List<Usuario> usuarios = await this.service.GetUsuariosAsync();
            return View(usuarios);
        }


        public IActionResult CreateUsuario()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUsuario(Usuario usu)
        {
            await this.service.InsertUsuarioAsync(usu.IdUsuario, usu.Password, usu.Nombre, usu.Apellidos, usu.Email, usu.Telefono, usu.IDRole);
            return RedirectToAction("UsuariosView");
        }

        public async Task<IActionResult> ModificarUsuario(int idUsuario)
        {
            Usuario usuario = await this.service.GetUsuarioAsync(idUsuario);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        [HttpPost]
        public IActionResult ModificarUsuario(Usuario usu)
        {
            this.service.UpdateUsuarioAsync(usu.IdUsuario, usu.Password, usu.Nombre, usu.Apellidos, usu.Email, usu.Telefono, usu.IDRole);
            return RedirectToAction("UsuariosView");
        }

        public async Task<IActionResult> DeleteUsuario(int idUsuario)
        {
            await this.service.DeleteUsuarioAsync(idUsuario);
            return RedirectToAction("UsuariosView");
        }

        //JUEGOS
        public async Task<IActionResult> JuegosView()
        {
            List<Juego> juegos = await this.service.GetJuegosAsync();
            return View(juegos);
        }

        public async Task<IActionResult> CreateJuego()
        {
            List<Genero> generos = await this.service.GetGenerosAsync();
            List<Editor> editores = await this.service.GetEditoresAsync();

            ViewData["GENEROS"] = generos;
            ViewData["EDITORES"] = editores;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateJuego(Juego juego, IFormFile imagen)
        {
            await this.storageBlobs.UploadBlobAsync("imgs", imagen.FileName, imagen.OpenReadStream());
            juego.ImagenJuego = await this.storageBlobs.GetBlobUrlAsync("imgs", imagen.FileName);
            await this.service.InsertJuegoAsync(juego.IdJuego, juego.NombreJuego, juego.IDGenero, juego.ImagenJuego, juego.PrecioJuego, juego.Descripcion, juego.IdEditor);
            return RedirectToAction("JuegosView");
        }

        public async Task<IActionResult> ModificarJuego(int idJuego)
        {
            Juego juego = await this.service.GetJuegoAsync(idJuego);
            List<Genero> generos = await this.service.GetGenerosAsync();
            List<Editor> editores = await this.service.GetEditoresAsync();

            ViewData["GENEROS"] = generos;
            ViewData["EDITORES"] = editores;
            return View(juego);
        }

        [HttpPost]
        public async Task<IActionResult> ModificarJuego(Juego juego)
        {
            await this.service.UpdateJuegoAsync(juego.IdJuego, juego.NombreJuego, juego.IDGenero, juego.ImagenJuego, juego.PrecioJuego, juego.Descripcion, juego.IdEditor);
            return RedirectToAction("JuegosView");
        }

        public async Task<IActionResult> DeleteJuego(int idJuego)
        {
            await this.service.DeleteJuegoAsync(idJuego);
            return RedirectToAction("JuegosView");
        }

        //Generos
        public async Task<IActionResult> GenerosView()
        {
            List<Genero> generos = await this.service.GetGenerosAsync();
            return View(generos);
        }

        public IActionResult CreateGenero()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateGenero(Genero genero)
        {
            await this.service.InsertGeneroAsync(genero.IdGenero, genero.NombreGenero);
            return RedirectToAction("GenerosView");
        }

        public async Task<IActionResult> ModificarGenero(int idGenero)
        {
            Genero genero = await this.service.GetGeneroAsync(idGenero);
            return View(genero);
        }

        [HttpPost]
        public async Task<IActionResult> ModificarGenero(Genero genero)
        {
            await this.service.UpdateGeneroAsync(genero.IdGenero, genero.NombreGenero);
            return RedirectToAction("GenerosView");
        }

        public async Task<IActionResult> DeleteGenero(int idGenero)
        {
            await this.service.DeleteGeneroAsync(idGenero);
            return RedirectToAction("GenerosView");
        }

        //Editores
        public async Task<IActionResult> EditoresView()
        {
            List<Editor> editores = await this.service.GetEditoresAsync();
            return View(editores);
        }

        public IActionResult CreateEditor()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateEditor(Editor editor)
        {
            await this.service.InsertEditorAsync(editor.IDEditor, editor.NombreEditor);
            return RedirectToAction("EditoresView");
        }

        public async Task<IActionResult> ModificarEditor(int idEditor)
        {
            Editor editor = await this.service.GetEditorAsync(idEditor);
            return View(editor);
        }

        [HttpPost]
        public async Task<IActionResult> ModificarEditor(Editor editor)
        {
            await this.service.UpdateEditorAsync(editor.IDEditor, editor.NombreEditor);
            return RedirectToAction("EditoresView");
        }

        public async Task<IActionResult> DeleteEditor(int idEditor)
        {
            await this.service.DeleteEditorAsync(idEditor);
            return RedirectToAction("EditoresView");
        }
    }
}

PulseGamingMVC/Controllers/JuegosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using PulseGamingMVC.Data;
using PulseGamingMVC.Extensions;
using PulseGamingMVC.Filters;
using PulseGamingMVC.Models;
using PulseGamingMVC.Repositories;
using PulseGamingMVC.Services;
using System;
using System.Security.Claims;

namespace PulseGamingMVC.Controllers
{
    public class JuegosController : Controller
    {
        private IRepositoryJuegos repo;
        private IMemoryCache memoryCache;
        private ServicePulseGaming service;
        private ServiceCacheRedis serviceCache;

        public JuegosController(IRepositoryJuegos repo, IMemoryCache memoryCache, ServicePulseGaming service, ServiceCacheRedis serviceCache)
        {
            this.service = service;
            this.repo = repo;
            this.memoryCache = memoryCache;
            this.serviceCache = serviceCache;
        }

        public IActionResult Inicio()
        {
            return View();
        }

        public async Task<IActionResult> JuegosFavoritos()
        {
            List<Juego> juegos = await this.serviceCache.GetJuegosFavoritosAsync();
            return View(juegos);
        }

        public async Task<IActionResult> Games(string precio, string search, int? posicion, int? idfavorito)
        {

            ViewData["PRECIO"] = precio;

            if (posicion == null)
            {
                posicion = 1;
            }
            int numeroRegistros = await this.service.GetNumeroJuegosAsync();
            ViewData["REGISTROS"] = numeroRegistros;
            ViewData["POSICION"] = posicion;

            if (precio == "desc")
            {
                var juegosDesc = await this.service.GetJuegosPrecioDescAsync();
                return View(juegosDesc);
            }
            else if(precio == "asc")
            {
                var juegosasc = await this.service.GetJuegosPrecioAsceAsync();
                return View(juegosasc);
            }
            else
            {
                List<Juego> juegos = await this.service.GetGrupoJuegosAsync(posicion.Value);
                return View(juegos);
            }

        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> AñadirFavorito(int idjuego)
        {
            Juego juego = await this.service.GetJuegoAsync(idjuego);
            await this.serviceCache.AddJuegoFavoritoAsync(juego);
            return RedirectToAction("Games");
        }

        public async Task<IActionResult> DeleteFavorito(int idjuego)
        {
            await this.serviceCache.DeleteJuegoFavoritoAsync(idjuego);
            return RedirectToAction("JuegosFavoritos");
        }

        public async Task<IActionResult> Details(int IdJuego)
        {
            Juego juegoDetalle = await this.service.GetJuegoAsync(IdJuego);
            return View(juegoDetalle);
        }

        public async Task<IActionResult> ListarJuegosCategorias(int idgenero)
        {
            List<Juego> juegosCategorias = await this.service.GetJuegosGenerosAsync(idgenero);
            return View(juegosCategorias);
        }

        public async Task<IActionResult> Carrito()
        {
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (carrito != null)
            {
                List<Juego> juegos = await this.repo.GetJuegosSessionAsync(carrito);
                return View(juegos);
            }
            return View();
        }

        public IActionResult AñadirCarrito(int? idJuego)
        {
            if (idJuego != null)
            {
                List<int> carrito;
                if (HttpContext.Session.GetString("CARRITO") == null)
                {
                    carrito = new List<int>();
                }
                else
                {
                    carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
                }
                carrito.Add(idJuego.Value);
                HttpContext.Session.SetObject("CARRITO", carrito);
            }
            return RedirectToAction("Games");
        }

        [HttpPost]
        public IActionResult AñadirAlCarritoDesdeLista(int? idJuego)
        {

            if (idJuego != null)
            {
                List<int> carrito;
                if (HttpContext.Session.GetString("CARRITO") == null)
                {
                    carrito = new List<int>();
                }
                else
                {
                    carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
                }
                carrito.Add(idJuego.Value);
                HttpContext.Session.SetObject("CARRITO", carrito); 
            }

            return RedirectToAction("Carrito");
        }

        public async Task<IActionResult> EliminarJuegoCesta(int? idJuego)
        {
            if (idJuego != null)
            {
                List<int> carrito =
                    HttpContext.Session.GetObject<List<int>>("CARRITO");
                carrito.Remove(idJuego.Value);
                if (carrito.Count() == 0)
                {
                    HttpContext.Session.Remove("CARRITO");
                }
                else
                {
                    HttpContext.Session.SetObject("CARRITO", carrito);
                }
            }
            return RedirectToAction("Carrito");
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> RealizarCompra()
        {
            var idusuario = int.Parse(HttpContext.User.FindFirst("IdUsuario").Value);

            // Obtenemos la lista de productos en la cesta desde la sesión
            List<int> cesta = HttpContext.Session.GetObject<List<int>>("CARRITO");

            // Obtenemos los detalles de los productos en la cesta desde la base de datos
            List<Juego> productosEnCarrito = await this.repo.GetProductosEnCarritoAsync(cesta);

            // Creamos el pedido
            await this.service.InsertPedidoAsync(idusuario, productosEnCarrito);

            // Limpiamos la cesta después de crear el pedido
            HttpContext.Session.Remove("CARRITO");

            // Redirigimos a alguna página de confirmación o cualquier otra acción que necesites
            return RedirectToAction("Games");
        }

        public async Task<IActionResult> PedidosUsuario()
        {
            var idUsuario = int.Parse(HttpContext.User.FindFirst("IdUsuario").Value);
            List<DetallePedidoView> pedidosUsuarios = await this.service.GetProductosPedidoUsuarioAsync(idUsuario);
            return View(pedidosUsuarios);
        }
    }
}

PulseGamingMVC/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using PulseGamingMVC.Services;
using System.Security.Claims;
using PulseGamingMVC.Models;

namespace PulseGamingMVC.Controllers
{
    public class ManagedController : Controller
    {
        private ServicePulseGaming service;

        public ManagedController(ServicePulseGaming service)
        {
            this.service = service;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            string token = await this.service
                .GetTokenAsync(model.Email, model.Password);
            if (token == null)
            {
                ViewData["MENSAJE"] = "Email/Password incorrectos";
                return View();
            }
            else
            {
                Usuario? usuario = (await service.GetUsuariosAsync())
                    .Where(user => user.Email.Equals(model.Email)
                    && user.Password.Equals(model.Password))
                    .FirstOrDefault();
                    
                HttpContext.Session.SetString("TOKEN", token);
                ClaimsIdentity identity =
                    new ClaimsIdentity
                    (CookieAuthenticationDefaults.AuthenticationScheme
                    , ClaimTypes.Email, "Password");
                identity.AddClaim
                    (new Claim(ClaimTypes.Email, model.Email));
                identity.AddClaim
                    (new Claim("Password", model.Password));
                identity.AddClaim
                    (new Claim("TOKEN", token));
                identity.AddClaim(new Claim("IdUsuario", usuario!.IdUsuario.ToString()));
                identity.AddClaim(new Claim(ClaimTypes.Role, usuario.IDRole.ToString()));
                ClaimsPrincipal userPrincipal =
                    new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync
                    (CookieAuthenticationDefaults.AuthenticationScheme
                    , userPrincipal, new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.UtcNow.AddMinutes(30)
                    });
                return RedirectToAction("Inicio", "Juegos");
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Inicio", "Juegos");
        }
    }
}

PulseGamingMVC/ViewComponents/MenuCategoriasViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PulseGamingMVC.Models;
using PulseGamingMVC.Repositories;

namespace PulseGamingMVC.ViewComponents
{
    public class MenuCategoriasViewComponent : ViewComponent
    {
        private IRepositoryJuegos repo;

        public MenuCategoriasViewComponent(IRepositoryJuegos repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Genero> generos = await this.repo.GetGenerosAsync();
            return View(generos);
        }
    }
}

PulseGamingMVC/Views/Shared/_Layout.cshtml
@{
    List<Juego> favoritos = memoryCache.Get<List<Juego>>("FAVORITOS");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PulseGamingMVC</title>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/icons/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">
    <link rel="stylesheet" href="~/css/Inicio.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Games.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Registro.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Dashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Details.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PulseGamingMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Juegos" asp-action="Inicio">Pulse Gaming</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link botonesCustom" asp-area="" asp-controller="Juegos" asp-action="Inicio">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link botonesCustom" asp-area="" asp-controller="Juegos" asp-action="Games">Juegos</a>
                        </li>
                        @await Component.InvokeAsync("MenuCategorias")
                        <li class="nav-item">
                            <a asp-controller="Juegos" asp-action="JuegosFavoritos" class="nav-link botonesCustom">Favoritos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link botonesCustom" asp-area="" asp-controller="Juegos" asp-action="Carrito">Carrito</a>    
                        </li>
                    </ul>
                    <ul class="navbar-nav float-end">
                        <li class="nav-item dropdown">
                            <button type="button" class="botonesCustom" class="dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-person-circle"></i>
                            </button>
                            <ul class="dropdown-menu">
                                <partial name="_MenuUsuario" />
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main class="">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="container">
            &copy; 2024 - PulseGamingMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PulseGamingMVC/Views/Shared/_MenuUsuario.cshtml
@using System.Security.Claims


@if (Context.User.Identity.IsAuthenticated)
{
    var userRole = int.Parse(Context.User.FindFirst(claim => claim.Type == ClaimTypes.Role).Value);
    if (userRole == 1) // Si el rol del usuario es administrador
    {
        <li>
            <a class="dropdown-item" asp-controller="Usuarios" asp-action="Perfil">
                Mi perfil
            </a>
        </li>
        <li>
            <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Dashboard">
                Dashboard
            </a>
        </li>
        <li>
            <a class="dropdown-item text-dark" asp-controller="Juegos" asp-action="PedidosUsuario">
                Mis pedidos
            </a>
        </li>
    }
    else
    {
        <li>
            <a class="dropdown-item" asp-controller="Usuarios" asp-action="Perfil">
                Mi perfil
            </a>
        </li>
        <li>
            <a class="dropdown-item text-dark" asp-controller="Juegos" asp-action="PedidosUsuario">
                Mis pedidos
            </a>
        </li>
    }
    <li>
        <a class="dropdown-item"
            asp-controller="Managed" asp-action="Logout">
            LogOut
        </a>
    </li>
    
}
else
{
    <li><a class="dropdown-item" asp-area="" asp-controller="Usuarios" asp-action="Perfil">Log-In</a></li>
    <li><a class="dropdown-item" asp-area="" asp-controller="Usuarios" asp-action="RegistrarUsuario">Register</a></li>
}