PulseGamingMVC/Models/Usuario.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace PulseGamingMVC.Models
{
    [Table("Usuarios")]
    public class Usuario
    {
        [Key]
        [Column("IDUsuario")]
        public int IdUsuario { get; set; }
        [Column("Password")]
        public string Password { get; set; }
        [Column("Nombre")]
        public string Nombre { get; set; }
        [Column("Apellidos")]
        public string Apellidos { get; set; }
        [Column("Email")]
        public string Email { get; set; }
        [Column("Telefono")]
        public int Telefono { get; set; }
        [Column("IDRole")]
        public int IDRole { get; set; }
    }
}

PulseGamingMVC/Controllers/JuegosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using PulseGamingMVC.Data;
using PulseGamingMVC.Extensions;
using PulseGamingMVC.Filters;
using PulseGamingMVC.Models;
using PulseGamingMVC.Repositories;
using PulseGamingMVC.Services;
using System;
using System.Security.Claims;

namespace PulseGamingMVC.Controllers
{
    public class JuegosController : Controller
    {
        private IRepositoryJuegos repo;
        private IMemoryCache memoryCache;
        private ServicePulseGaming service;
        private ServiceCacheRedis serviceCache;

        public JuegosController(IRepositoryJuegos repo, IMemoryCache memoryCache, ServicePulseGaming service, ServiceCacheRedis serviceCache)
        {
            this.service = service;
            this.repo = repo;
            this.memoryCache = memoryCache;
            this.serviceCache = serviceCache;
        }

        public IActionResult Inicio()
        {
            return View();
        }

        public async Task<IActionResult> JuegosFavoritos()
        {
            List<Juego> juegos = await this.serviceCache.GetJuegosFavoritosAsync();
            return View(juegos);
        }

        public async Task<IActionResult> Games(string precio, string search, int? posicion, int? idfavorito)
        {

            ViewData["PRECIO"] = precio;

            if (posicion == null)
            {
                posicion = 1;
            }
            int numeroRegistros = await this.service.GetNumeroJuegosAsync();
            ViewData["REGISTROS"] = numeroRegistros;
            ViewData["POSICION"] = posicion;

            if (precio == "desc")
            {
                var juegosDesc = await this.service.GetJuegosPrecioDescAsync();
                return View(juegosDesc);
            }
            else if(precio == "asc")
            {
                var juegosasc = await this.service.GetJuegosPrecioAsceAsync();
                return View(juegosasc);
            }
            else
            {
                List<Juego> juegos = await this.service.GetGrupoJuegosAsync(posicion.Value);
                return View(juegos);
            }

        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> AñadirFavorito(int idjuego)
        {
            Juego juego = await this.service.GetJuegoAsync(idjuego);
            await this.serviceCache.AddJuegoFavoritoAsync(juego);
            return RedirectToAction("Games");
        }

        public async Task<IActionResult> DeleteFavorito(int idjuego)
        {
            await this.serviceCache.DeleteJuegoFavoritoAsync(idjuego);
            return RedirectToAction("JuegosFavoritos");
        }

        public async Task<IActionResult> Details(int IdJuego)
        {
            Juego juegoDetalle = await this.service.GetJuegoAsync(IdJuego);
            return View(juegoDetalle);
        }

        public async Task<IActionResult> ListarJuegosCategorias(int idgenero)
        {
            List<Juego> juegosCategorias = await this.service.GetJuegosGenerosAsync(idgenero);
            return View(juegosCategorias);
        }

        public async Task<IActionResult> Carrito()
        {
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (carrito != null)
            {
                List<Juego> juegos = await this.repo.GetJuegosSessionAsync(carrito);
                return View(juegos);
            }
            return View();
        }

        public IActionResult AñadirCarrito(int? idJuego)
        {
            if (idJuego != null)
            {
                List<int> carrito;
                if (HttpContext.Session.GetString("CARRITO") == null)
                {
                    carrito = new List<int>();
                }
                else
                {
                    carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
                }
                carrito.Add(idJuego.Value);
                HttpContext.Session.SetObject("CARRITO", carrito);
            }
            return RedirectToAction("Games");
        }

        [HttpPost]
        public IActionResult AñadirAlCarritoDesdeLista(int? idJuego)
        {

            if (idJuego != null)
            {
                List<int> carrito;
                if (HttpContext.Session.GetString("CARRITO") == null)
                {
                    carrito = new List<int>();
                }
                else
                {
                    carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
                }
                carrito.Add(idJuego.Value);
                HttpContext.Session.SetObject("CARRITO", carrito); 
            }

            return RedirectToAction("Carrito");
        }

        public async Task<IActionResult> EliminarJuegoCesta(int? idJuego)
        {
            if (idJuego != null)
            {
                List<int> carrito =
                    HttpContext.Session.GetObject<List<int>>("CARRITO");
                carrito.Remove(idJuego.Value);
                if (carrito.Count() == 0)
                {
                    HttpContext.Session.Remove("CARRITO");
                }
                else
                {
                    HttpContext.Session.SetObject("CARRITO", carrito);
                }
            }
            return RedirectToAction("Carrito");
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> RealizarCompra()
        {
            var idusuario = int.Parse(HttpContext.User.FindFirst("IdUsuario").Value);

            // Obtenemos la lista de productos en la cesta desde la sesión
            List<int> cesta = HttpContext.Session.GetObject<List<int>>("CARRITO");

            // Obtenemos los detalles de los productos en la cesta desde la base de datos
            List<Juego> productosEnCarrito = await this.repo.GetProductosEnCarritoAsync(cesta);

            // Creamos el pedido
            await this.service.InsertPedidoAsync(idusuario, productosEnCarrito);

            // Limpiamos la cesta después de crear el pedido
            HttpContext.Session.Remove("CARRITO");

            // Redirigimos a alguna página de confirmación o cualquier otra acción que necesites
            return RedirectToAction("Games");
        }

        public async Task<IActionResult> PedidosUsuario()
        {
            var idUsuario = int.Parse(HttpContext.User.FindFirst("IdUsuario").Value);
            List<DetallePedidoView> pedidosUsuarios = await this.service.GetProductosPedidoUsuarioAsync(idUsuario);
            return View(pedidosUsuarios);
        }
    }
}

PulseGamingMVC/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using PulseGamingMVC.Helpers;
using PulseGamingMVC.Models;
using PulseGamingMVC.Repositories;
using PulseGamingMVC.Extensions;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.AspNetCore.Http.HttpResults;
using PulseGamingMVC.Services;
using PulseGamingMVC.Filters;


namespace PulseGamingMVC.Controllers
{
    public class UsuariosController : Controller
    {
        private ServicePulseGaming service;
        private IRepositoryUsuarios repo;

        public UsuariosController(ServicePulseGaming service, IRepositoryUsuarios repo)
        {
            this.service = service;
            this.repo = repo;
        }

        public IActionResult RegistrarUsuario()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegistrarUsuario(Usuario usu)
        {
            await this.service.InsertUsuarioAsync(usu.IdUsuario, usu.Password, usu.Nombre, usu.Apellidos, usu.Email, usu.Telefono, usu.IDRole);
            return RedirectToAction("Perfil");
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Perfil()
        {
            Usuario usuario = await this.service.GetPerfilUsuarioAsync();
            return View(usuario);
        }
    }
}

PulseGamingMVC/Views/Usuarios/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<div class="login-card">
    <h1>Log-in</h1><br>

    <form method="post">
        <input type="text" name="email" placeholder="Email">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" name="login" class="login login-submit" value="login">
    </form>

    <div class="login-help">
        <a asp-action="RegistrarUsuario" asp-controller="Usuarios">Registrate</a> • <a asp-action="RegistrarUsuario" asp-controller="Usuarios">¿Olvidaste Contraseña?</a>
    </div>
</div>

<h1>@ViewData["MENSAJE"]</h1>

PulseGamingMVC/Views/Usuarios/Perfil.cshtml
@model PulseGamingMVC.Models.Usuario

@{
    ViewData["Title"] = "Perfil";
}

<h1>Perfil de Usuario</h1>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Games" asp-controller="Juegos">Inicio</a>
</div>

PulseGamingMVC/Views/Usuarios/RegistrarUsuario.cshtml
@{
    ViewData["Title"] = "Registro";
}

<div class="register-card">
    <form method="post">
        <h1>Registro</h1><br>
        <input type="text" name="nombre" placeholder="Nombre">
        <input type="text" name="apellidos" placeholder="Apellidos">
        <input type="text" name="email" placeholder="Email">
        <input type="password" name="password" placeholder="Password">
        <input type="text" name="telefono" placeholder="Telefono">
        <input type="text" name="IDRole" value="2" readonly>
        <input type="submit" name="registro" class="register register-submit" value="Registro">
    </form>
    <p class="text-center">
        ¿Ya tienes cuenta?
    </p>
    <div class="register-help">
        <a asp-action="Login" asp-controller="Usuarios">Login</a>
    </div>
</div>

<h1>@ViewData["MENSAJE"]</h1>